spring:
  datasource:
    url: ENC(uwAD+ze5BriXjxYbPqKxqugnHpTv4S892LcnAFgl9XRRpCaHMkjJK2FBZqwklkCXoX9eJ0LaTKmXEzrouQFF2EXqUG/CdSGCJIdpnQPzt3XCR/tSfcVCQI5O891b1Oudsx+dhNap7zGX5AyiGjkvuTxNxSWTAxM8shWFJHUrR+Y=)
    username: ENC(1B2TwIHH5eR2PZ/p7Q87qw==)
    password: ENC(Vb+2F6gupIvEzGG70jPcZ+YYbs88FOOR)
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        #        show_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect

