spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        #        show_sql: true
        highlight_sql: true
        use_sql_comments: true

baseball:
  maxAnswerCount: 10
