spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/hotel-java?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: devktak
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        #        show_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
