spring:
  datasource:
    url: jdbc:h2:mem:baseball
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
