spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        #        show_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect

baseball:
  maxAnswerCount: 10
